version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: socks-db
    environment:
      POSTGRES_DB: socks-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "7654:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: